name: env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10  # or whichever version you prefer
  - numpy>=1.16.4,<2.0
  - scipy>=1.4.1
  - pandas~=1.4.3
  - matplotlib>=3.7.2
  - scikit-learn>=1.3.0
  - seaborn
  - ipykernel
  - pip
  - pip:
    - dendropy>=4.4.0
    - tqdm>=4.66.1
    - rpy2>=3.5.16